name: Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_TOKEN,REPO
          script: |
            cd ~/couples-app
            git pull https://x-access-token:$GITHUB_TOKEN@github.com/$REPO.git main
            chmod +x deploy.sh
            ./deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
